DATA_ROOT = 'static/'

ASSAY_FILE_PATH = DATA_ROOT + 'assay_CATNAP.txt'

VIRUS_SEQ = DATA_ROOT + "virseqs_aa_CATNAP.fasta"

ANTIBODY_LIGHT_CHAIN_SEQ = DATA_ROOT + "light_seqs_aa_CATNAP_ALIGNED.fasta"
ANTIBODY_HEAVY_CHAIN_SEQ = DATA_ROOT + "heavy_seqs_aa_CATNAP_ALIGNED.fasta"

RANDOM_SPLIT = DATA_ROOT + 'random_split_indexes'

INTERVALS_UPPER_BOUND = 150

K_NEIBHOURS = 10

